Type the reducer
cabify/redux-polyglot pull request #3
Opened 2018-12-12 15:45 UTC by cicloon

Properly type the reducer.

2018-12-12 15:50 UTC, humanrender requested changes

2018-12-12 15:50 UTC, humanrender commented on src/types.d.ts
> +        state: PolyglotState = { locale: null, phrases: null },
Does this compile? shouldn't it be ?
```
locale: string | null
```

2018-12-12 17:38 UTC, inspiratweb approved these changes
👍

2018-12-13 09:10 UTC, cicloon commented
@humanrender fixed

2018-12-13 09:12 UTC, humanrender approved these changes

2018-12-13 09:46 UTC, merged